project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!Local Only/"

website:
  title: "AI Resources"
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: false
  favicon: Images/DSDE-Social-Media-Profile.png
  search: true
  repo-url: https://github.com/ysph-dsde/ai-resources-page
  issue-url: https://github.com/ysph-dsde/ai-resources-page/issues
  repo-actions: [source, issue]
  navbar:
    right:
      - text: "Policies"
        href: Pages/policies.qmd
      - text: "Courses & Programs"
        href: Pages/resources.qmd
      - text: "AI Tools"
        href: Pages/tools.qmd
      - text: "Feedback"
        menu:
          - text: "For Yale Affiliates"
            href: https://forms.office.com/Pages/ResponsePage.aspx?id=u76M3Tkh-E20EU4-h6vrXH-TvKDg8gZHqoE3FAMavy5UQTNGVDlWSFZOVUVNMUsxWktNTUdMS1lVRS4u
            target: _blank
          - text: "For Non-Yale Affiliates"
            href: https://forms.office.com/Pages/ResponsePage.aspx?id=u76M3Tkh-E20EU4-h6vrXH-TvKDg8gZHqoE3FAMavy5UNlNFQkJCSlE3NkZMT1JIN0tPWEJTVkFWTi4u
            target: _blank
      - text: "About Us"
        href: Pages/about-us.qmd
      - text: "Contact"
        href: https://ysph.yale.edu/public-health-research-and-practice/research-centers-and-initiatives/public-health-data-science-and-data-equity/contact-us/
        target: _blank
  page-footer:
    background: light 
    left: "This site is hosted on [ysph-dsde.github.io](https://github.com/ysph-dsde), rendered with Quarto (v1.6.3), and styled using a modified version of [flatly](https://github.com/thomaspark/bootswatch) with Yale School of Public Health branding, incorporating Data Science and Data Equity color schemes." 
    center:
      - text: "Policies"
        href: Pages/policies.qmd
      - text: "Courses & Programs"
        href: Pages/resources.qmd
      - text: "Tools"
        href: Pages/tools.qmd
      - text: "About Us"
        href: Pages/about-us.qmd
      - text: "Contact"
        href: https://ysph.yale.edu/public-health-research-and-practice/research-centers-and-initiatives/public-health-data-science-and-data-equity/contact-us/
    right: 
      - icon: globe
        href: https://ysph.yale.edu/public-health-research-and-practice/research-centers-and-initiatives/public-health-data-science-and-data-equity/
      - icon: github
        href: https://github.com/ysph-dsde
      - icon: linkedin
        href: https://www.linkedin.com/showcase/public-health-data-science-and-data-equity-at-yale/
      - icon: envelope 
        href: mailto:admin.dsdeysph@yale.edu
      - text: "(203) 737-8644"

format:
  html:
    include-in-header: 
      - _includes/google_analytics.html
      - _includes/functional_scripts.html
      #- _includes/feedback_popup.html
    header-includes:
      - <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
      - <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
    toc: true
    toc-depth: 4
    theme:
      - flatly
      - _styles/styles.scss
    from: markdown+autolink_bare_uris


editor: source
filters:
    - parse-latex

markdown: 
  editor_options: 
    chunk_output_type: console
